apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosreport-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sosreport-operator
  template:
    metadata:
      labels:
        name: sosreport-operator
    spec:
      serviceAccountName: sosreport-operator
      containers:
        - name: sosreport-operator
          # Replace this with the built image name
          image: quay.io/bostrt/sosreport-operator
          command:
          - sosreport-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sosreport-operator"
